appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: DsLG1v83lokSRimPaI/UjTC7p9F3QYfEUlkXfPJ+XPAVb4O5aUZmBY/zTOurO4B26XqZO98hPLEZjB8e3q+rMeL2oVfYj47qS6eOZyHcfON00jzjn/LabsoeTF13nBJ828z0SDftqrfxUVyqW/gULOB+Mm6a9oeQaWHoKiSRcMNQWXz0x/VmPr59yv+j2ID0tse1aoUI5m8c+pmJc6CeE/qhFn8/3rK17v0lVxTk3x7bqmD3C3LDPUCWhBnqp8XMEeSqwaAo4LaveRCGOWOJL32QoBmfc+PSS1OgAUfrNwcEgV3tuuVh4lqDfSzH5m92KDLH3I0ADOpbATda85BSQyFDTDfNn9sY/GUGojoo6zJ/aoqkSMuqnroD/poW260XlLIuCMxUuKDERi0U00NaImSK/LqBXPPeMAKTPghN3lSX7TgvxfCfX7pLtUebolmif1IXmCastHSZOET2xI2h3KmXTY73YmWkn/JGYCX0p5DD4df1yqqyjuZw/75Jug/uap4sIsblomBE9HZ3RkU3i+MOGHEkSJ/6rj0+3ZKeiWK00U8a/evdl5tlm28MR4QoMaKdwohYrjJ/BUvwdbSynvqZZfGlW2lCHOMzEABTC2CQGcFkq7y34mzwy2Nei/7FM52VGGc9ClEulGgFzBP2NXwy5dLf7sDc2ViC+qds08M=
conda_forge_output_validation: false
